services:
  - type: web
    name: echolink-frontend
    runtime: node
    plan: starter
    region: oregon
    branch: main
    buildCommand: npm install && npm run build
    startCommand: npm run start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_WORDPRESS_API_ENDPOINT
        sync: false
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASSWORD
        sync: false
      - key: CONTACT_TO_EMAIL
        sync: false
      - key: PORT
        value: 10000
